### ISSUE TITLE
support for NoSQL systems

### ISSUE THREAD

**Issue by mscsf15m027** [chetui/CloudSuiteTutorial#1]
According to my search I figure out that cloudsuite only support cassendra,memcached,Spark. Is there anyone else for which cloudsuite benchmark can be used? I have visited your official website as well and find these three systems benchmarking with different workloads. Actually i want to know about the all those NoSQL systems which are supported by cloudsuite. Kindly help me.

**Comment by chetui** [comment]
This repo is a non-official tutorial for CloudSuite, which is recorded by the way when I was using CloudSuite. 
I notice you already create an issue in the official repo of CouldSuite in https://github.com/parsa-epfl/cloudsuite/issues/83 . So I will close the issue here, and hope they can help you in that issue.

As for your question, AFAIK, the systems that you can find in the official website (including cassendra, memcached, spark that you mentioned) are the only ones supported by CloudSuite. 
Because CouldSuite is a benchmark. It just needs to pick up some typical systems and does not need support all systems.
